class Field:
    username_textfield = "//input[@id='user-name']"
    username_passwordfield = "//input[@id='password']"
    login_button = "//input[@id='login-button']"
    product_span = "//span[@class='title']"
    sort_order = "//select[@class='product_sort_container']/option[text()='Price (high to low)']"
    item1 = "//button[@id='add-to-cart-sauce-labs-fleece-jacket']"
    item2 = "//button[@id='add-to-cart-sauce-labs-bolt-t-shirt']"
    item3 = "//button[@id='add-to-cart-sauce-labs-bike-light']"
    cart = "//a[@class='shopping_cart_link']"
    checkout = "//button[@id='checkout']"
    checkout_first_name = "//input[@id='first-name']"
    checkout_last_name = "//input[@id='last-name']"
    checkout_zip_code = "//input[@id='postal-code']"
    checkout_continue = "//input[@id='continue']"
    item_total = "//div[@class='summary_subtotal_label'][normalize-space()='Item total: $75.97']"
    total = "//div[@class='summary_total_label'][normalize-space()='Total: $82.05']"
    tax = "//div[@class='summary_tax_label'][normalize-space()='Tax: $6.08']"

    home_page = "//span[@class='title'][contains(text(),'Products')]"
    numer_of_items_in_cart = "//span[@class='shopping_cart_badge'][contains(text(),'3')]"
    cart_page = "//span[@class='title'][contains(text(),'Your Cart')]"
    checkout_page = "//span[@class='title']"
    fname_valuse = "//input[@id='first-name'][@value='John']"
    checkout_overview = "//span[@class='title'][contains(text(),'Checkout: Overview')]"
